### ISSUE TITLE
Didn't investigate why, but this script freezes my Xcode's GUI debugger

### ISSUE THREAD

**Issue by lanza** [gdbinit/lldbinit#1]
Thought my Xcode was bugged or some work-related configuration was bugging up my Xcode lldb until I just guessed to comment out the line that sources this. Sure enough, Xcode went back to work like normal. Obviously not crucial or anything, just a heads up.

**Comment by 0xbf00** [comment]
Same here, this took me a while to figure out. With this script in place, Xcode barely works at all. Running, testing and debugging all hang Xcode, requiring a force quit.

**Comment by gdbinit** [comment]
It was due to lacking Xcode detection and then a bad fix for it. Everything should work with latest commit.
