### ISSUE TITLE
error: module importing failed: unindent does not match any outer indentation level (lldbinit.py, line 2071)

### ISSUE THREAD

**Issue by dothanthitiendiettiende** [gdbinit/lldbinit#17]
error: module importing failed: unindent does not match any outer indentation level (lldbinit.py, line 2071)

[            print("[-] error: invalid register for i386 architecture.")](https://github.com/gdbinit/lldbinit/blob/1fe8df74ccd80836ddae73da4207dc63fcaf388a/lldbinit.py#L2070)

**Comment by dmaclach** [comment]
There are multiple PRs now to fix this problem. Any chance you could pull on of them in?

**Comment by dmaclach** [comment]
#12 specifically should fix this up. Thanks!
