### ISSUE TITLE
On Mojave, get lots of issues

### ISSUE THREAD

**Issue by ronaaron** [gdbinit/lldbinit#4]
Starting with the 'return outside function' which was already reported, but fixing that I then have lldb complain about importing 'argparse'

**Comment by graves** [comment]
It's still broken on: 

`MacOS Catalina 10.15.6`

which uses:

```
lldb-1200.0.32
Apple Swift version 5.3 (swiftlang-1200.0.28.1 clang-1200.0.30.1)
```

I've submitted a pull request here: https://github.com/gdbinit/lldbinit/pull/9 that fixes the issues. It includes the two previously opened (and still open) pull requests which were never merged or acknowledged. If this project is abandoned feel free to use my fork: https://github.com/graves/lldbinit/tree/lldb-python3-api-fixes
